#include <assert.h>
#include <mysqlx/xdevapi.h>
#include <iostream>
#include <list>
#include <string>
#include <vector>

#include "file_utils.hpp"

struct
{
  std::string host = "localhost";
  std::string user = "root";
  std::string pwd = "353213";
  std::string db = "test";
  unsigned short port = 33060;
} config;

int main(int argc)
{
  using std::cout;
  using std::endl;
  using namespace mysqlx;

  try {
    Session sess("localhost", 33060, "root", "353213");
    {
      // get version
      RowResult res = sess.sql("show variables like 'version'").execute();
      std::stringstream version;

      version << res.fetchOne().get(1).get<string>();
      int major_version;
      version >> major_version;
      if (major_version < 8) {
        cout << "major_version < 8!" << endl;
        return 0;
      }
    }

    // get all schema
    {
      std::vector<Schema> schemas = sess.getSchemas();
      cout << "schemas name: " << endl;
      for (unsigned i = 0; i < schemas.size(); ++i) {
        std::cout << "#" << i << ": " << schemas[i].getName() << endl;
      }
    }

    cout << "Session accepted, creating collection..." << endl;
    Schema sch = sess.getSchema(config.db, true);
    Collection coll = sch.createCollection("my_collection", true);
    coll.remove("true").execute();  // remove all
    
    DocResult docs;
    DbDoc doc;
    Result res;
    {
      cout << "Add json data: " << endl;
      {
        res = coll.add(FileUtils::readFile("menu.json"))
                  .add(FileUtils::readFile("widget.json"))
                  .add(R"({ "name": "Shang San", "age": 18, "sex": 0 })")
                  .execute();
        std::list<DbDoc> ls = {DbDoc(R"({ "name": "Susanne", "age": 24 })"), DbDoc(R"({ "name": "User", "age": 39 })")};
        res = coll.add(ls).execute();

        // Warning
        {
          std::vector<Warning> warnings = res.getWarnings();
          for (auto w : warnings) {
            cout << "Warning: " << w << endl;
          }
        }

        // getGeneratedIds
        {
          res = coll.add(R"({ "_id": "custom_id", "abc" : 1 })").execute();
          std::vector<string> ids = res.getGeneratedIds();
          if (ids.empty()) {
            cout << "No Autogenerated ids" << endl;
          }

          res = coll.add(R"({ "cd" : 1 })").execute();
          std::vector<string> ids2 = res.getGeneratedIds();
          for (auto id : ids2) {
            cout << "Autogenerated ids= " << id << endl;
          }
        }
      }

      cout << "Show collection/docs: " << endl;
      {
        docs = coll.find().execute();  // 所有的doc/json
        doc = docs.fetchOne();
        for (int i = 0; !doc.isNull(); ++i, doc = docs.fetchOne()) {
          cout << "#" << i << ": " << doc << endl;

          // 解析doc/json
          for (Field field : doc) {  // value = doc[field]
            cout << "-fild `" << field << "`: " << doc[field] << endl;
          }
          /*
          {
            "id" : "file", "value" : "File", "menuitem" : [
              {"value" : "New", "onclick" : "CreateNewDoc()"}, {"value" : "Open", "onclick" : "OpenDoc()"},
              {"value" : "Close", "onclick" : "CloseDoc()"}
            ]
          }
          */
          if (doc.hasField("menuitem") && doc.fieldType("menuitem") == Value::ARRAY) {
            cout << "\t-menuitem: " << endl;
            for (DbDoc d : doc["menuitem"]) {  // 进入[...]
              for (Field f : d) {              // 进入{...}
                cout << "\t-fild `" << f << "`: " << d[f] << endl;
              }
            }
          }
          /*
          {
            "debug" : "on", "window":
            {
              "title" : "Sample Konfabulator Widget", "name" : "main_window", "width" : 500, "height" : 500
            }
          }
          */
          if (doc.hasField("window") && doc.fieldType("window") == Value::DOCUMENT) {
            DbDoc d = doc["window"];
            for (Field f : d) {  // 进入{...}
              cout << "\t-fild `" << f << "`: " << d[f] << endl;
            }
          }
        }
      }

      cout << "Find: " << endl;
      {
        cout << "-find one: " << endl;
        docs = coll.find("name like :param").limit(1).bind("param", "S%").execute();
        cout << "\t-" << docs.fetchOne() << endl;

        cout << "-find all: " << endl;
        docs = coll.find("name like :param").sort("age DESC").limit(2).bind("param", "S%").execute();
        while (DbDoc doc = docs.fetchOne()) {
          cout << "\t-" << doc << endl;
        }
      }

      cout << "Remove: " << endl;
      {
        cout << "-remove one: " << endl;
        res = coll.remove("age > 0").limit(1).execute();
        cout << "affect count: " << res.getAffectedItemsCount() << endl;

        cout << "-remove all: " << endl;
        docs = coll.find("age > 0").execute();
        while (doc = docs.fetchOne()) {
          res = coll.removeOne(doc["_id"]);
          cout << "\t-id: " << doc["_id"] << endl;
        }
      }

      cout << "modify: " << endl;
      {
        res = coll.add(R"({ "name": "Susanne", "age": 24 })").execute();
        coll.modify("age==24").set("age", 100).execute();

        res = coll.add(R"({ "name": ["abc", "123"], "age": 25 })").execute();
        coll.modify("age==25").arrayAppend("name", "456").execute();

        coll.modify("age==25").arrayInsert("name[1]", "456").execute();
      }

      cout << "addOrReplaceOne: " << endl;
      {
        res = coll.addOrReplaceOne("custom_id", DbDoc(R"({ "abc": 25 })"));
        cout << "affect count: " << res.getAffectedItemsCount() << endl;
      }

      cout << "getOne: " << endl;
      {
        res = coll.add(DbDoc(R"({ "abc": 25, "cd": 100 })")).execute();
        std::vector<string> ids = res.getGeneratedIds();
        std::cout << coll.getOne(ids[0]) << endl;
      }

      cout << "count: " << endl;
      {
        cout << coll.count() << endl;
      }
    }

    cout << "Session accepted, get table..." << endl;
    Table table = sch.getTable("my_table");
    table.remove().execute();

    res = table.insert("name", "age").values("User", 28).values("Jack", 26).execute();
    RowResult result = table.select().execute();
    while (Row row = result.fetchOne()) {
      cout << row << endl;
    }

  } catch (const mysqlx::Error &err) {
    cout << "ERROR: " << err << endl;
    return 1;
  } catch (std::exception &ex) {
    cout << "STD EXCEPTION: " << ex.what() << endl;
    return 1;
  } catch (const char *ex) {
    cout << "EXCEPTION: " << ex << endl;
    return 1;
  } catch (...) {
    cout << "UNKONW ERROR!" << endl;
    return 2;
  }

  return 0;
}